server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
 
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto:  update

  h2:
    console:
      enabled: true
      path: /h2-ui


validation:
  messages:
    errors:
      20001:
        field: price
        message: Product price must not exceed $10,000
        code: 20001
      20002:
        field: price
        message: Product name can't be null
        code: 20002
      20003:
        field: price
        message: Product can't be null
        code: 20003
      100001:
        field: consumerKey
        message: X-CONSUMER-KEY can't be null or empty
        code: 100001
